### PR TITLE
Create MSA summary files and close #9 

### LINKED ISSUE #9: Create NCDB data sets for entire Washington MSA
NCDB data for the MSA are needed for new Greater DC initiative web site. cc: @rpitingolo @lhendey

### PR DESCRIPTION
**Pull request by ptatian**

### CODE REVIEW

**Comment by ptatian** [comment]
Need to revise programs to convert 2000 to 2010 tracts. First must complete [General repo issue 25](https://github.com/NeighborhoodInfoDC/General/issues/25) to create tract weighting files.

**Comment by rpitingolo** [comment]
@ptatian I think I have this finished. Can you please review?

**Comment by ptatian** [comment]
@rpitingolo OK, taking a look now.

**Comment by ptatian** [comment]
@rpitingolo Looks good. But I found a mistake in the 2010 file I created earlier. It had _tr00 in the data set name, even though the data are 2010 tracts. I pushed changes to **Ncdb_2010_sum_was15.sas** to fix this as well as wrote a new program to delete the old file. I also moved all of the 2010 programs to a subfolder.  

So, to finalize, please batch submit the following after merging and syncing changes.

- Prog\Ncdb_sum_was15.sas
- Prog\2010\Delete_Ncdb_sum_2010_was15_tr00.sas
- Prog\2010\Ncdb_2010_sum_was15.sas

**Comment by ptatian** [comment]
@rpitingolo Sorry! Found one last small change. Please stand by.

**Comment by rpitingolo** [comment]
@ptatian ok, standing by.

**Comment by rpitingolo** [comment]
@ptatian when you are finished, can you please indicate which programs need to be batch submitted on L? I don't want to miss anything.

**Comment by ptatian** [comment]
@rpitingolo OK, all set now. Thanks.

**Comment by ptatian** [comment]
@rpitingolo Just these. 

- Prog\Ncdb_sum_was15.sas
- Prog\2010\Delete_Ncdb_sum_2010_was15_tr00.sas
- Prog\2010\Ncdb_2010_sum_was15.sas

**Comment by rpitingolo** [comment]
I'm going to batch submit Ncdb_sum_was15.sas and Ncdb_2010_sum_was15.sas, correct?

**Comment by rpitingolo** [comment]
@ptatian thanks. going to merge now.

**Pull request merged**
