### PR TITLE
Create Ncdb_sum_all.sas

### PR DESCRIPTION
**Pull request by eburton9**
@rpitingolo ward 2022 showed up and no errors!!

### CODE REVIEW

**Comment by rpitingolo** [comment]
@eburton9 I am getting errors when I run it, unfortunately. Not immediately clear what's wrong. I am investigating.

**Comment by rpitingolo** [comment]
@eburton9 all the geographies are working except the tract geography. It's hard to de-bug this one because of how the macro in the General library is written but I'm still working on it.

**Comment by rpitingolo** [comment]
@eburton9 OK I think I got it by adding a new parameter on to the macro. Please pull down my edit, then run it again and if no errors you can go ahead and merge and final batch submit. Thanks!

**Comment by eburton9** [comment]
Received "ERROR: The keyword parameter INCLUDE_TRACTS was not defined with the macro."

**Comment by rpitingolo** [comment]
Did you have a previous SAS session still open? Try restarting SAS so it can recompile the macros from General.

**Comment by eburton9** [comment]
Yeah I just tried again to close out of SAS and the virtual desktop and restart them all, same thing. I still don't get errors on my local with the original program without the two new lines.. (i find that weird but maybe that's normal)

**Comment by rpitingolo** [comment]
OK we will have to troubleshoot this one on one because I don't have this issue.

**Pull request merged**
